# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    worker_job_processor_publish:
        class: AppBundle\Job\Publish
        arguments:
            - "@doctrine.orm.entity_manager"
            - '%kernel.root_dir%'    
        
    time_format_twig_service:
        class: AppBundle\Twig\Extension\TimeFormatExtension
        arguments:
            - '@time_format_service'
        tags:
            - { name: "twig.extension" }

    time_format_service:
        class: AppBundle\Formatter\TimeFormatter
